/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.*;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.nashorn.internal.runtime.regexp.joni.Config;

public class GUI extends javax.swing.JFrame {

    static int number_of_roles = 0;
    public int color = 0;

    public GUI() {
        initComponents();
    }

    public int number_of_roles(double n) {
        double no2 = Double.parseDouble(width.getText());
        number_of_roles = (int) (Math.ceil(no2 / 4));
        return number_of_roles;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hight = new javax.swing.JTextField();
        width = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        l = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program/logo_7.png"))); // NOI18N

        hight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hightActionPerformed(evt);
            }
        });

        width.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("ادخل طول الملعب  ");

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText("ادخل عرض الملعب");

        label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label4.setText("كم لون للملعب؟");

        button1.setActionCommand("botton1");
        button1.setBackground(new java.awt.Color(0, 204, 0));
        button1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button1.setLabel("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(0, 204, 0));
        button2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        button2.setLabel("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        l.setColumns(20);
        l.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        l.setRows(5);
        l.setTabSize(18);
        l.setCaretColor(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(l);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);

                // this for save photo
                File file_img = new File(number_of_roles+".png");
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1514, 1514, 1514)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hight, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jButton1)
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(357, 357, 357))
        );

        label2.getAccessibleContext().setAccessibleName("طول الملعب");
        button1.getAccessibleContext().setAccessibleName("botton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1442, 1442, 1442))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        ImageIcon image;

        double no2 = Double.parseDouble(width.getText());
        int number_of_roles = number_of_roles(no2);

        double new_Width = no2 / number_of_roles;
        l.setText("Number of rolls are: " + (int) (number_of_roles) + " ,where width of each roll is:" + String.format("%,.1f", new_Width));
        switch ((int) number_of_roles) {
            case 5:
                image = new ImageIcon("two\\5.jpg");
                jLabel2.setIcon(image);
                break;
            case 6:
                image = new ImageIcon("two\\6.png");
                jLabel2.setIcon(image);
                break;
            case 7:
                image = new ImageIcon("two\\7.jpg");
                jLabel2.setIcon(image);
                break;
            case 8:
                image = new ImageIcon("two\\8.jpg");
                jLabel2.setIcon(image);
                break;
            case 9:
                image = new ImageIcon("two\\9.jpg");
                jLabel2.setIcon(image);
                break;
            case 10:
                image = new ImageIcon("two\\10.jpg");
                jLabel2.setIcon(image);
                break;
            case 11:
                image = new ImageIcon("two\\11.jpg");
                jLabel2.setIcon(image);
                break;
            case 12:
                image = new ImageIcon("two\\12.jpg");
                jLabel2.setIcon(image);
                break;
            case 13:
                image = new ImageIcon("two\\13.jpg");
                jLabel2.setIcon(image);
                break;
            case 14:
                image = new ImageIcon("\\two\\14.jpg");
                jLabel2.setIcon(image);
                break;
            case 15:
                image = new ImageIcon("two\\15.jpg");
                jLabel2.setIcon(image);
                break;
            case 16:
                image = new ImageIcon("two\\16.jpg");
                jLabel2.setIcon(image);
                break;
            case 17:
                image = new ImageIcon("two\\17.jpg");
                jLabel2.setIcon(image);
                break;
            case 18:
                image = new ImageIcon("two\\18.jpg");
                jLabel2.setIcon(image);
                break;
            case 19:
                image = new ImageIcon("two\\19.jpg");
                jLabel2.setIcon(image);
                break;
            case 20:
                image = new ImageIcon("two\\20.jpg");
                jLabel2.setIcon(image);
                break;
            case 21:
                image = new ImageIcon("two\\21.png");
                jLabel2.setIcon(image);
                break;
            case 22:
                image = new ImageIcon("two\\22.jpg");
                jLabel2.setIcon(image);
                break;
            case 23:
                image = new ImageIcon("two\\23.jpg");
                jLabel2.setIcon(image);
                break;
            case 24:
                image = new ImageIcon("two\\24.jpg");
                jLabel2.setIcon(image);
                break;
            case 25:
                image = new ImageIcon("two\\25.jpg");
                jLabel2.setIcon(image);
                break;
            case 26:
                image = new ImageIcon("two\\26.jpg");
                jLabel2.setIcon(image);
                break;
            case 28:
                image = new ImageIcon("two\\28.png");
                jLabel2.setIcon(image);
                break;
            case 30:
                image = new ImageIcon("two\\30.png");
                jLabel2.setIcon(image);
                break;

        }


    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        color = 1;
        ImageIcon image;
        double no1 = Double.parseDouble(hight.getText());
        double number_of_roles = Math.ceil(no1 / 4);
        double new_Width = no1 / number_of_roles;

        l.setText("Number of rolls are: " + (int) (number_of_roles) + " ,where width of each roll is:" + String.format("%,.1f", new_Width));

        switch ((int) number_of_roles) {
            case 5:
                image = new ImageIcon("one_color\\5-1.png");
                jLabel2.setIcon(image);
                break;
            case 6:
                image = new ImageIcon("one_color\\6-1.png");
                jLabel2.setIcon(image);
                break;
            case 7:
                image = new ImageIcon("one_color\\7-1.png");
                jLabel2.setIcon(image);
                break;
            case 8:
                image = new ImageIcon("one_color\\8-1.png");
                jLabel2.setIcon(image);
                break;
            case 9:
                image = new ImageIcon("one_color\\9-1.png");
                jLabel2.setIcon(image);
                break;
            case 10:
                image = new ImageIcon("one_color\\10-1.png");
                jLabel2.setIcon(image);
                break;
            case 11:
                image = new ImageIcon("one_color\\11-1.png");
                jLabel2.setIcon(image);
                break;
            case 12:
                image = new ImageIcon("one_color\\12-1.png");
                jLabel2.setIcon(image);
                break;
            case 13:
                image = new ImageIcon("one_color\\13-1.png");
                jLabel2.setIcon(image);
                break;
            case 14:
                image = new ImageIcon("one_color\\14-1.png");
                jLabel2.setIcon(image);
                break;
            case 15:
                image = new ImageIcon("one_color\\15-1.png");
                jLabel2.setIcon(image);
                break;
            case 16:
                image = new ImageIcon("one_color\\16-1.png");
                jLabel2.setIcon(image);
                break;
            case 17:
                image = new ImageIcon("one_color\\17-1.png");
                jLabel2.setIcon(image);
                break;
            case 18:
                image = new ImageIcon("one_color\\18-one.png");
                jLabel2.setIcon(image);
                break;
            case 19:
                image = new ImageIcon("one_color\\19-1.png");
                jLabel2.setIcon(image);
                break;
            case 20:
                image = new ImageIcon("one_color\\20-one.png");
                jLabel2.setIcon(image);
                break;
            case 21:
                image = new ImageIcon("one_color\\21-one.png");
                jLabel2.setIcon(image);
                break;
            case 22:
                image = new ImageIcon("one_color\\22-one.png");
                jLabel2.setIcon(image);
                break;
            case 23:
                image = new ImageIcon("one_color\\23-one.png");
                jLabel2.setIcon(image);
                break;
            case 24:
                image = new ImageIcon("one_color\\24-one.png");
                jLabel2.setIcon(image);
                break;
            case 25:
                image = new ImageIcon("one_color\\25-one.png");
                jLabel2.setIcon(image);
                break;
            case 26:
                image = new ImageIcon("one_color\\26-one.png");
                jLabel2.setIcon(image);
                break;

        }

    }//GEN-LAST:event_button1ActionPerformed

    private void hightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hightActionPerformed

        //    jTextPane1.add( One_color( no1));
    }//GEN-LAST:event_hightActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser file=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("2 supported Extension", "jpg","png");
          file.setFileFilter(filter);
          int select = file.showSaveDialog(null);
//        try {
//           // java.io.PrintWriter output = new java.io.PrintWriter(file);
//           //
////            double no2 = Double.parseDouble(width.getText());
////            double new_Width = no2 / number_of_roles(no2);
////            output.print("Number of rolls are: " + (int) (number_of_roles) + " ,where width of each roll is:" + String.format("%,.1f", new_Width));
////            output.print("one_color\\26-one.png");
//           
//
//
//        } catch (FileNotFoundException ex) {
//            System.out.println("");
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * "* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button button1;
    public java.awt.Button button2;
    public javax.swing.JTextField hight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea l;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    public javax.swing.JTextField width;
    // End of variables declaration//GEN-END:variables

}
